### ISSUE TITLE
Oversized popup in Firefox

### ISSUE THREAD

**Issue by realedk** [RockSolid1106/LTT-Sidebar-customizer#19]
### **SOLVED**
**Describe the bug**
When I open the extension on Firefox after install, or after minimizing and then maximizing the Firefox page, the extension becomes oversized. It does not always recreate, just most of the time

**To Reproduce**
1. Open Firefox and load extension
2. Minimize the tab
3. Maximize the tab

**Expected behavior**
Normal sized window

**Screenshots**
The console did not show anything.
![2850337F-5778-47FC-984E-95C555D08BF0](https://user-images.githubusercontent.com/83384667/142914467-afdc5bd2-5afd-4bc7-8f6f-b0436f095f9d.jpeg)

**Comment by RockSolid1106** [comment]
I'm aware of this issue, but can't really figure out why it occurs. I'm pretty sure it's the CSS. I've tried to make it so where if the width is greater than 420px, it treats it as a mobile, and displays it accordingly. This is done so that the elements don't look too small on mobiles, because the pixel density on mobile is much higher. 

I'm now just removing it for mobile.

**Comment by RockSolid1106** [comment]
~~Reopening so people know this is a known issue. I will push the update when I have some more features to add cuz FF doesn't allow me to push an update without incrementing the version number, and I don't want to waste a version number just for that and cause inconsistent version numbers across the different platforms.~~

**Comment by RockSolid1106** [comment]
Since the last update(v0.8.8), I haven't seen this issue occur to me again. I'm not sure what caused this issue, but it's probably because of the increase in height of the popup, as new configuration options were added.

I'm leaving this issue open for a while, so if anyone of you encounters this issue, you can comment here.

Rock

**Comment by realedk** [comment]
I can also confirm it is not occurring.

**Comment by RockSolid1106** [comment]
**_This issue has been identified and will be fixed in the next update._**

**Comment by RockSolid1106** [comment]
**<-- This issue has been fixed with the latest update, v0.9.0. -->**
